import type { NextPage } from 'next'
import Head from 'next/head'
import Router from 'next/router'

const Home: NextPage = () => {

  Router.push('/dashboard');

  return (
    <div>
      <Head>
        <title>KonsPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
