import type { GetServerSideProps, NextPage } from 'next'
import { getSession } from 'next-auth/react';
import Head from 'next/head'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false
      }
    }
  }
  return {
    redirect: {
      destination: '/dashboard',
      permanent: false
    }
  }
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>KonsPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
